play.http.secret.key="changeme"

search {
  uri = "http://elasticsearch:9200"
}

analyzer {
  urls = [
    "/opt/Cortex-Analyzers/analyzers"
  ]
  fork-join-executor {
    parallelism-min = 2
    parallelism-factor = 2.0
    parallelism-max = 4
  }
}

responder {
  urls = [
    "/opt/Cortex-Analyzers/responders"
  ]
}

job {
  runner = [process]
  directory = /tmp/cortex-jobs
}
