play.http.secret.key="changeme"

search {
  uri = "http://192.168.1.129:9200"
}

analyzer {
  urls = [
    "/opt/Cortex-Analyzers/analyzers"
  ]
}

responder {
  urls = [
    "/opt/Cortex-Analyzers/responders"
  ]
}
