version: "3.7"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    restart: unless-stopped
    mem_limit: 1g
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    networks:
      - soc_net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - soc_net

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.9
    container_name: logstash
    restart: unless-stopped
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    networks:
      - soc_net

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.9
    container_name: filebeat
    user: root
    restart: unless-stopped
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - logstash
    networks:
      - soc_net


  cassandra:
    image: cassandra:4
    container_name: cassandra
    restart: unless-stopped
    volumes:
      - cassandradata:/var/lib/cassandra
    networks:
      - soc_net

  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: unless-stopped
    command: minio server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data
    networks:
      - soc_net

  cortex:
    image: thehiveproject/cortex:latest
    container_name: cortex
    restart: unless-stopped
    depends_on:
      - elasticsearch
    ports:
      - "9002:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cortex/application.conf:/cortex/application.conf
    networks:
      - soc_net

  thehive:
    image: strangebee/thehive:5.2
    container_name: thehive
    restart: unless-stopped
    depends_on:
      - cassandra
      - elasticsearch
      - minio
      - cortex
    ports:
      - "9003:9000"
    command:
      - --secret
      - lab123456789
      - --cql-hostnames
      - cassandra
      - --index-backend
      - elasticsearch
      - --es-hostnames
      - elasticsearch
      - --s3-endpoint
      - http://minio:9000
      - --s3-access-key
      - minioadmin
      - --s3-secret-key
      - minioadmin
    volumes:
      - thehivedata:/opt/thehive/data
    networks:
      - soc_net

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - soc_net

  misp_mysql:
    image: mysql/mysql-server:5.7
    container_name: misp_mysql
    restart: unless-stopped
    volumes:
      - mispsqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mispdb
      MYSQL_USER: mispuser
      MYSQL_PASSWORD: misppass
      MYSQL_ROOT_PASSWORD: misppass
    networks:
      - soc_net

  misp:
    image: coolacid/misp-docker:core-latest
    container_name: misp
    restart: unless-stopped
    depends_on:
      - misp_mysql
      - redis
    ports:
      - "80:80"
      - "443:443"
    environment:
      MYSQL_HOST: misp_mysql
      MYSQL_DATABASE: mispdb
      MYSQL_USER: mispuser
      MYSQL_PASSWORD: misppass
      MISP_BASEURL: https://localhost
    networks:
      - soc_net

volumes:
  miniodata:
  cassandradata:
  elasticsearchdata:
  thehivedata:
  mispsqldata:

networks:
  soc_net:
    driver: bridge
